# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86b12b21da2c5eb77b06aeee8219cc14bd0f418d516f3597379965f86597eb07d1786fda130799a1ac71f0eb43f7d81c56414f4cdcc178c42d20796678dd82eb

test:
  secret_key_base: 9476fa2700af2e40c333733f0f21974088fb6a1682e43129c139ad01da2d7854c84708501fbe53f41cb0621d4baf7212aa6c780cad6b939d29991387d8f263be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
